default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: eleicoes_2012
  password: '123'
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: eleicao_2012_development

test:
  <<: *default
  database: eleicao_2012_test

production:
  <<: *default
  database: eleicao_2012_production
